// <auto-generated />
using System;
using ApplePodcastTranscription.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApplePodcastTranscription.Migrations
{
    [DbContext(typeof(ApplePodcastDbContext))]
    partial class ApplePodcastDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ApplePodcastTranscription.Models.DbTables.PodcastRecord", b =>
                {
                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtistName")
                        .HasColumnType("TEXT");

                    b.Property<long>("DownloadedAtInUnixTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<long>("TranscribedAtInUnixTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranscriptionText")
                        .HasColumnType("TEXT");

                    b.HasKey("ExternalId");

                    b.ToTable("PodcastsRecords");
                });

            modelBuilder.Entity("ApplePodcastTranscription.Models.DbTables.TranscriptSession", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtInUnixTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PodcastRecordId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TranscriptionError")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TranscriptionStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.HasIndex("PodcastRecordId");

                    b.ToTable("TranscriptSessions");
                });

            modelBuilder.Entity("ApplePodcastTranscription.Models.DbTables.TranscriptSession", b =>
                {
                    b.HasOne("ApplePodcastTranscription.Models.DbTables.PodcastRecord", "PodcastRecord")
                        .WithMany("Sessions")
                        .HasForeignKey("PodcastRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PodcastRecord");
                });

            modelBuilder.Entity("ApplePodcastTranscription.Models.DbTables.PodcastRecord", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
