// <auto-generated />
using System;
using ApplePodcastTranscription.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApplePodcastTranscription.Migrations
{
    [DbContext(typeof(ApplePodcastDbContext))]
    partial class ApplePodcastDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ApplePodcastTranscription.Models.PodcastRecord", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("DownloadedAtInUnixTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TranscribedAtInUnixTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TranscriptionError")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TranscriptionStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranscriptionText")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.ToTable("PodcastsRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
